package org.alvas.autogeneratedid;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

import com.aiet1.hibernetproject1.dto.User;

public class EmployeeController {

	public static void main(String[] args) {
		EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("vikas");
		EntityManager entityManager = entityManagerFactory.createEntityManager();
		EntityTransaction entityTransaction = entityManager.getTransaction();
		Employee emp= new Employee();
		//emp.setId(143);
		emp.setName("Athul");
		emp.setEmail("athul@gmail.com");
		
		entityTransaction.begin();
		entityManager.persist(emp);

		entityTransaction.commit();


	}

}
